let newsS = [
    {   number : "1",
        title : "Primeiro brasileiro a alcançar o 7º Dan em Iaido",
        image : "../src/images/photos/alexandre-sensei-7dan(1).jpg",
        imageAlt : 'Alexandre sensei executando uma estocada (tsuki-sashi).',
        imageTitle :'Alexandre sensei executando uma estocada (tsuki-sashi).',
        date : "02/03/2025",
        text : 'No dia 02 de março de 2025, em Quioto, o Sensei Alexandre Pereira, Muso Jikiden Eishin Ryu, é o brasileiro com a maior graduação (Renshi 7º Dan) pela Federação Japonesa de Kendo (Zen Nihon Kendo Renmei - ZNKR). Um marco significativo para as artes marciais e o Iaido no Brasil. A conquista, que exige anos de dedicação, habilidade e conhecimento profundo, consolida a posição do Sensei Alexandre como um respeitado expoente da modalidade, sendo o primeiro brasileiro a alcançar esse patamar. O feito foi celebrado por seus alunos e colegas.<img class="news-image" src="../src/images/photos/alexandre-sensei-7dan(2).jpg" alt="Alexandre sensei comemorando o seu 7º Dan "em família", ganhou um sageo novo verde e amarelo, sob encomenda. "Afinal, apesar de ter mais tempo de vida no Japão, continuo brasileiro!"><p id="img-title">Alexandre sensei comemorando o seu 7º Dan "em família", ganhou um sageo novo verde e amarelo, sob encomenda. "Afinal, apesar de ter mais tempo de vida no Japão, continuo brasileiro!</p>',
        link : "",
        tags: "notícias noticia iaido brasileiro exame sensei alexandre março"
    },
    {   number : "2",
        title : "Seminário de Iaido e Jodo com Oshita sensei (Kyoshi, 8º Dan) e Otake sensei (Hanshi, 8º Dan) em Nova Iorque (04/04/2025 a 07/04/2025)",
        image : "../src/images/photos/2025-seminário-jodo-iaido-novayork(1).jpg",
        imageAlt : "Da esquerda para a direita, Otake sensei (Hanshi, 8º Dan), Jose Arenas (4º Dan) e Oshita sensei (Kyoshi, 8º Dan)",
        imageTitle :"Da esquerda para a direita, Otake sensei (Hanshi, 8º Dan), Jose Arenas (4º Dan) e Oshita sensei (Kyoshi, 8º Dan)",
        date : "22/04/2025",
        text : 'No primeiro final de semana de abril de 2025, Oshita sensei (Kyoshi, 8º Dan) e Otake sensei (Hanshi, 8º Dan) visitaram Nova Iorque para realizar um seminário duplo de Iaido e Jodo, organizado por Pam Parker sensei (Kyoshi, 7º Dan). Sexta e sábado o trabalho intenso em Jodo contou com Otake Sensei como guia do seminário e Oshita Sensei como colaborador. Domingo e segunda, durante o seminário de Iaido, os papeis se invertiram. O seminário foi simplesmente maravilhoso. Ter dois Sensei deste calibre, que além de serem grandes expoentes das duas artes são excelentes instrutores e pedagogos, é uma experiência única. A mistura da excelente demonstração técnica por parte deles, a clareza na explicação de detalhes e um humor vivo por parte dos dois fez com que a dor nos pés e o cansaço ficasse em um segundo plano. Todas as pessoas queriam aprender e treinar mais.<p> Os seminários focaram em aspectos básicos, trabalhando exclusivamente Seitei Iai e Seitei jo. Muitas dúvidas foram esclarecidas, deixando uma ênfase clara: todo movimento de corte deve começar de forma relaxada e sem força; a força (e não tensão) só deve ser aplicada logo antes de que a espada (ou o jo) atinjam seu alvo. No Jodo, o treino prezou pela troca frequente de parceiros de treino, de forma que todo mundo, independentemente do grau e experiência, trabalhasse com pessoas mais avançadas, mas também mais iniciantes. Isso ajuda com que os iniciantes elevem um pouco seu nível ao se desafiarem, e com que as pessoas mais avançadas modifiquem sua técnica, timming e feeling para se acomodarem às necessidades específicas da pessoa com quem estão treinando. Um último ponto que gostaria de destacar aqui: os dos Sensei enfatizaram a necessidade de que o uso da espada no Jodo deve ser mais realista e precisa. Só assim o verdadeiro Jodo pode surgir.</p><p>No Iaido, o treino foi dividido inicialmente em dois grandes grupos: Mudan (sem Dan ou faixas brancas) até Sandan (3º dan) e Yondan (4º dan) até Nanadan (7º dan). Os dois Sensei se revezaram na instrução de cada grupo, de forma que puderam compartilhar diferentes detalhes com todo mundo. Dentre muitas, a principal diferença foi o timing no saque da espada, a união e fluidez nos movimentos, e no uso do metsuke para a demonstração de zanshin. Foi muito interessante ver como dois Sensei de tão alto nível podem ter diferentes formas de fazer um mesmo movimento. Para não esquecer: 1. enquanto Oshita Sensei explicava o timing correto do saque no Morotetsuki, pediu para que 5 pessoas fizessem o primeiro movimento ao mesmo tempo (com a distancia e segurança adequada), tendo ele como possível inimigo. Assim que o grupo começou o movimento, Oshita Sensei começou também, e simplesmente cortou na direção das 5 pessoas antes de todas elas tivessem terminado seu saque. 2. Explicando as possibilidades do Ukenagashi, Oshita Sensei fez um Ukenagashi virando 180 graus para um inimigo que estava atrás dele. Esse é um movimento que ele costuma fazer para falar da importância de entender e executar bem uma técnica, mas é simplesmente FENOMENAL.</p><img class="news-image" src="../src/images/photos/2025-seminário-jodo-iaido-novayork(2).jpg" alt="Da esquerda para a direita, Oshita sensei (Kyoshi, 8º Dan), Otake sensei (Hanshi, 8º Dan) e Jose Arenas (4º Dan)."><p id="img-title">Da esquerda para a direita, Oshita sensei (Kyoshi, 8º Dan), Otake sensei (Hanshi, 8º Dan) e Jose Arenas (4º Dan).</p><p>Enfim, foram 4 dias de muito trabalho, de muito treino, de encontros com pessoas muito bacanas e de treinar com dois grandes Sensei do Iaido e Jodo. Agradeço à Parker Sensei por ter convidado Oshita e Otake sensei e por ter organizado este evento. Agradeço também ao trabalho do Aurelian Sensei e Furuta Sensei na sua tradução, e a todas as pessoas envolvidas na organização do evento.</p><br><p>(Texto e relato de Jose Arenas, 4º Dan Ken-Zen Iaido, Nova Iorque)</p>',
        link : "",
        tags: "notícias noticia iaido jodo seminário"
    },
    {   number : "3",
        title : "2º Campeonato Latinoamericano de Iaido 17/10/2025 a 19/10/2025 - Santiago, Chile",
        image : "../src/images/photos/2023-campeonato-latinoamericano-iaido.jpg",
        imageAlt : "Praticantes brasileiros de Iaido no campeonato.",
        imageTitle :"Praticantes brasileiros de Iaido no campeonato.",
        date : "01/05/2025",
        text : 'Entre os dias 17 e 19 de outubro de 2025, a capital chilena, Santiago, será palco do 2º Campeonato Latinoamericano de Iaido . O evento reunirá Kenshi e Sensei diversos países do continente americano. O campeonato busca fortalecer os laços entre os países da região e promover o intercâmbio técnico e cultural entre os praticantes de Iaido.  Aguardem mais informações!</p>',
        link : "",
        tags: "notícias noticia iaido américa latina"
    },
    {   number : "5",
        title : "Kyoto Taikai 2025",
        image : "../src/images/photos/2025-iaido-enbu-taikai.png",
        imageAlt : "121º Enbu Taikai (Encontro de Demonstração) da Zen Nihon Kendo.",
        imageTitle :"121º Enbu Taikai (Encontro de Demonstração) da Zen Nihon Kendo.",
        date : "02/05/2025",
        text : '<p>Neste fim de semana está ocorrendo o 121º Enbu Taikai (Encontro de Demonstração) da Zen Nihon Kendo. Acesse nos links abaixo os Enbu de Iaido do Kyoto Taikai de 2025:</p><a href="https://www.youtube.com/live/2ooVxGFqVTI?si=q9mJJdBEzkGjC26i" target="blank"><p>Kyoto Taikai 2025 - Canal 1</p></a><a href="https://www.youtube.com/live/-uk7iRpyyPI?si=WpmZejfhcYtlTCeP&t=13983" target="blank"><p>Kyoto Taikai 2025 - Canal 2</p></a>',
        link : "",
        tags: "notícias noticia iaido"
    },
    {   number : "6",
        title : "Participação do Alexandre Pereira Sensei no Seminário Central e Regional da ZNKR",
        image : "../src/images/photos/2025-seminário-central-e-regional-znkr1.jpg",
        imageAlt : "Mesa diretora do Seminário Central e Regional da ZNKR",
        imageTitle :"Mesa diretora do Seminário Central e Regional da ZNKR",
        date : "01/07/2025",
        text : 'Participação do Alexandre Pereira Sensei no Seminário Central e Regional da ZNKR, realizado na província de Ibaraki, nos dias 28 e 29 de junho de 2025.<img class="news-image" src="../src/images/photos/2025-seminário-central-e-regional-znkr5.jpg" alt="Placa do Seminário Central e Regional da ZNKR."><p id="img-title">Placa do Seminário Central e Regional da ZNKR.</p> <img class="news-image" src="../src/images/photos/2025-seminário-central-e-regional-znkr2.jpg" alt="Participantes do Seminário Central e Regional da ZNKR."><p id="img-title">Participantes do Seminário Central e Regional da ZNKR.</p> <img class="news-image" src="../src/images/photos/2025-seminário-central-e-regional-znkr3.jpg" alt="Participantes do Seminário Central e Regional da ZNKR."><p id="img-title">Participantes do Seminário Central e Regional da ZNKR.</p> <img class="news-image" src="../src/images/photos/2025-seminário-central-e-regional-znkr4.jpg" alt="Certificado de participação do seminário do Alexandre Pereira Sensei."><p id="img-title">Certificado de participação do seminário do Alexandre Pereira Sensei.</p>',
        link : "",
        tags: "notícias noticia iaido"
    },
    // {   number : "7",
    //     title : "",
    //     image : "",
    //     imageAlt : "",
    //     imageTitle :"",
    //     date : "",
    //     text : '',
    //     link : "",
    //     tags: "notícias noticia iaido"
    // },
    ]